### PR TITLE
Promises

### LINKED ISSUE #54: How will the Promise's onFulfilled handlers be implemented to be postponed until no script code is on the stack?
Hi,

I noticed you have started working on Promises, but did not yet implement handling the onFulfilled and onRejected handlers.
After reading through the Promises/A+ specification, I realized that these handlers are not invoked recursively, but instead postponed until no other script function is currently on the stack (which makes sense to avoid a StackOverflow when converting a loop to use promises).

For example. if you run:

``` javascript
console.log("1. Before resolve");
Promise.resolve(123).then(function() {
  console.log("2. Inside onResolved handler");
});
console.log("3. After resolve");
```

then the program prints:

```
1. Before resolve
3. After resolve
2. Inside onResolved handler
```

Do you have a thought of how to implement this so that the onFulfilled and onRejected handler's execution is postponed until no further script function is on the stack?

My thought was to have the ScriptEngine declaring a list of FunctionInstances that are to be invoked later, and a boolean that specifies if a function of this script engine is already on the stack:

``` c#
internal bool ScriptIsExecuting { get; set; }

internal List<FunctionInstance> ExecutionContextFunctionBuffer { get; } =
    new List<FunctionInstance>();
```

Then, maybe the FunctionInstance's `CallLateBound()` method could be changed to be not abstract but instead call an abstract `CallLateBoundCore()` function (and subclasses override the latter one instead of `CallLateBound()`), and the `CallLateBound()` can check if it needs to call the buffered function instances:

``` c#
public object CallLateBound(object thisObject, params object[] argumentValues)
{
    bool firstExecution = !Engine.ScriptIsExecuting;
    if (firstExecution)
        Engine.ScriptIsExecuting = true;

    try
    {
        var returnValue = CallLateBoundCore(thisObject, argumentValues);

        // Check if we are the first script function on the stack from this script engine
        // and we need to call buffered functions.
        if (firstExecution)
        {
            while (Engine.ExecutionContextFunctionBuffer.Count > 0)
            {
                List<FunctionInstance> copy =
                    new List<FunctionInstance>(Engine.ExecutionContextFunctionBuffer);
                Engine.ExecutionContextFunctionBuffer.Clear();

                foreach (var func in copy)
                    func.Call(Null.Value); // TODO

            }
        }

        return returnValue;
    }
    finally
    {
        if (firstExecution)
            Engine.ScriptIsExecuting = false;
    }
}
```

This way it would be ensured that if functions from multiple ScriptEngines are on the stack, the first function of each ScriptEngine on the stack will call the buffered FunctionInstances (this is currently how I do it in my code with a ES6-Promises Polyfill).

However, one issue is how to handle exceptions when FunctionInstances are buffered. For example, if you run this in Chrome:

``` javascript
Promise.resolve(123).then(function() {
  console.log("Inside onResolved handler");
});
throw new Error("My Error");
```

it will print on the console:

```
Inside onResolved handler
Uncaught Error: My Error(…)
```

So it will still call the onFulfilled handler and then throw the exception. This could be implemented by catching exceptions in the CallLateBound e.g. with `ExceptionDispatchInfo.Capture(ex)` to preserve the StackTrace when rethrowing it later, then running the buffered FunctionInstances and then rethrowing the exception. (I think the FunctionInstances shouldn't be run in a `finally` block as it marks a protected region of code and cannot be aborted with `Thread.Abort()`). 

Thanks!

### PR DESCRIPTION
**Pull request by jcdickinson**
This pull request completes the promise functionality. Closes #54.

### CODE REVIEW

File: Jurassic/Library/Promise/PromiseInstance.cs [hunk 1]
```diff
@@ -113,11 +157,45 @@ public PromiseInstance Catch(FunctionInstance onRejected)
...
+                ResolveOrReject(onRejected as FunctionInstance);
+            }
+            return this;
         }
 
+        /// <summary>
+        /// Creates a task that completes when this promise completes.
+        /// </summary>
+        /// <returns>The task that completes when this promise completes.</returns>
+        public Task<object> CreateTask()
```
Comment (jcdickinson) [inline Jurassic/Library/Promise/PromiseInstance.cs]: Might be useful to expose Tasks (or any awaitable, really) to JS during binding, as another PR?

**Comment by jcdickinson** [comment]
Oof. I noticed that these must be deferred until there is no code on the stack. Updating this to a WIP.

**Comment by jcdickinson** [comment]
This now conforms to the specification, ready for review.

File: Unit Tests/Library/PromiseTests.cs [hunk 2]
```diff
@@ -489,5 +491,160 @@ public async Task CreateTask()
...
+            var promise = TypeConverter.ToObject(jurassicScriptEngine, tcs.Task.GetAwaiter());
+            jurassicScriptEngine.SetGlobalValue("promise", promise);
+
+            Execute("promise.then(function (r) { testingContext.push(r) }, function (r) { throw r })");
+            Assert.AreEqual(0, (int)testingContext.Length);
+
+            tcs.SetResult(100);
+            Assert.AreEqual(0, (int)testingContext.Length);
+
+            jurassicScriptEngine.EventLoop.ExecutePendingCallbacks();
```
Comment (jcdickinson) [inline Unit Tests/Library/PromiseTests.cs]: NB: the developer has to `ExecutePendingCallbacks` (only when sending awaiters to JS) because there is no way to guarantee that the callbacks are happening in a thread-safe manner. JS-to-JS and JS-to-net callbacks are unaffected by this edge case and will automatically fire.

File: Jurassic/Library/Promise/PromiseInstance.cs (hunk 1 above)
Comment (jcdickinson) [reply Jurassic/Library/Promise/PromiseInstance.cs]: Added to this PR.

File: Unit Tests/Library/PromiseTests.cs (hunk 2 above)
Comment (kpreisser) [reply Unit Tests/Library/PromiseTests.cs]: Hi,
> because there is no way to guarantee that the callbacks are happening in a thread-safe manner

do I understand correctly that you are referring to the continuation on the callback/awaitable that could be called on any thread once the `Task` is completed?
In this case, when you call `ExecutePendingCallbacks()` here, while it will guarantee that callbacks added to the `Promise` are not called concurrently on another thread, it will only run them it they were already added to the EventLoop's pending callbacks list before calling the method.

For example, when you change this line:
```c#
        var tcs = new TaskCompletionSource<int>();
```
to
```c#
        var tcs = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
```
then the unit test may fail when the task completion did not occur prior to the call to `ExecutePendingCallbacks()`, and in that case if you never call `ExecutePendingCallbacks()` again, the JS callback will never be called even though the task continuation added the pending callback. Is this correct?

Please also note that there are still some parts of the Jurassic code that can be executed concurrently (due to `PromiseConstructor.Construct<T>(T notify)` registering a callback on the notify object) but are not thread-safe. For example, it calls `PromiseInstance.Resolve()` (or `.Reject()`) in the continuation thread, but that might access fields like `PromiseInstance.state` `fulfillReactions`.

I think this means there can be a race condition (as currently there is no locking):
Assume the main thread (A) calls some JS code that does `PromiseInstance.Then()` to add a callback to the promise. It checks the `state` which is `Pending`, so it goes to the branch where it will call `fulfillReactions.Add(...)`.

But if pauses before that call, another thread (B) (from the task continuation) can call `PromiseInstance.Resolve(...)`, which sets the state to `Fulfilled`, iterates over the `fulfillReactions` and then clears the list.

Now, assume thread A continues, and calls `fulfillReactions.Add()`. However, this callback will never execute as the promise was already set to `Fulfilled`.

Or, it could happen that thread A calls fulfillReactions.Add() while thread B is iterating over it, which could cause unexpected behavior as the list is not thread-safe.

I think this could be solved by adding some lock statements, but I'm not sure if we should do this.

Thank you!

**Comment by kpreisser** [comment]
Hi,
thank you very much for the PR! I'm looking forward to have Promises fully implemented in Jurassic, so I no longer need to use a polyfill for that functionality in our application.

I have skimmed through the PR, and added some comments. Overall, I think the PR looks good.
Thank you!

File: Unit Tests/Library/PromiseTests.cs (hunk 2 above)
Comment (jcdickinson) [reply Unit Tests/Library/PromiseTests.cs]: > do I understand correctly that you are referring to the continuation on the callback/awaitable that could be called on any thread once the Task is completed?

Correct.

> the JS callback will never be called even though the task continuation added the pending callback. Is this correct?

Probably not, but I can't see it working any other way, without making the whole of Jurassic thread-safe.

> adding some lock statements

I missed this completely and I'll go over the code again.

Comment (jcdickinson) [reply Unit Tests/Library/PromiseTests.cs]: FYI: locks in .Net [are basically free](https://web.archive.org/web/20130613185222/http://www.bluebytesoftware.com/blog/2007/06/24/CLRMonitorsAndSyncBlocks.aspx) until they first encounter contention.

File: Jurassic/Library/Promise/PromiseInstance.cs [hunk 3]
```diff
@@ -70,6 +56,61 @@ internal PromiseInstance(ObjectInstance prototype, FunctionInstance executor) :
...
+        internal object Reject(params object[] param) =>
+            ResolveOrReject(param, PromiseState.Rejected, rejectReactions);
+
+        internal object Resolve(params object[] param) =>
+            ResolveOrReject(param, PromiseState.Fulfilled, fulfillReactions);
+
+        internal object ResolveOrReject(object[] param, PromiseState state, List<FunctionInstance> functions)
+        {
+            if (this.state != PromiseState.Pending)
+                throw new JavaScriptException(Engine, ErrorType.TypeError, string.Format("Promise has already been {0}", this.state));
```
[the remark this answers is not in the document]
Comment (jcdickinson) [reply Jurassic/Library/Promise/PromiseInstance.cs]: There is no mention of an error in the spec, so I will remove it.

File: Jurassic/Library/Promise/PromiseInstance.cs [hunk 4]
```diff
@@ -29,13 +42,12 @@ internal enum PromiseState
...
 
         // 	A list of PromiseReaction records to be processed when/if the promise transitions
-        // from the Pending state to the Fulfilled state.
-        private readonly List<FunctionInstance> fulfillReactions = new List<FunctionInstance>();
-
-        // 	A list of PromiseReaction records to be processed when/if the promise transitions
-        // from the Pending state to the Rejected state.
-        private readonly List<FunctionInstance> rejectReactions = new List<FunctionInstance>();
+        // from the Pending state to any other state.
+        private readonly List<Reaction> reactions = new List<Reaction>(InitialReactionCapacity);
```
Comment (jcdickinson) [inline Jurassic/Library/Promise/PromiseInstance.cs]: NB: is now a single list. In async code it could possibly be expected that promises would be frequently allocated, so optimize allocations as much as possible.

Also, this helped with the Promises/A+ compliance.

**Comment by jcdickinson** [comment]
@kpreisser Thanks for the feedback! I went ahead and made sure that the implementation matches the Promises/A+ spec, so it now works alongside polyfilled promises.

**Comment by paulbartrum** [comment]
Thanks for this. I made a few minor changes (removed the EventLoop class, made ExecutePendingCallbacks internal, etc) but otherwise I merged in it's entirety.

**Comment by kpreisser** [comment]
Hi @paulbartrum,


> made ExecutePendingCallbacks internal

note that this method is currently only called from `GlobalMethodGenerator.Execute()` and `EvalMethodGenerator.Execute()`. However, e.g. if the script has registered some callbacks (`FunctionInstance`) which I want to call later, I would call `FunctionInstance.CallLateBound()`, but that does not execute the pending callbacks that the script registered some during execution of that function.

Therefore, I would need to call `ExecutePendingCallbacks()` manually after calling the `FunctionInstance`, so that method would need to be public.

(The other option I could imagine would be do do this directly in the `FunctionInstance`, but as you mentioned in #54, this is called a lot and could decrease performance.)

Thanks!

File: Jurassic/Compiler/MethodGenerator/EvalMethodGenerator.cs [hunk 5]
```diff
@@ -111,6 +111,9 @@ public object Execute(ScriptEngine engine)
             // Execute the compiled delegate and store the result.
             object result = ((GlobalCodeDelegate)this.GeneratedMethod.GeneratedDelegate)(engine, scope, this.ThisObject);
 
+            // Execute any pending event loop callbacks.
+            engine.EventLoop.ExecutePendingCallbacks();
```
Comment (kpreisser) [inline Jurassic/Compiler/MethodGenerator/EvalMethodGenerator.cs]: After writing my previous comment, I realized calling `ExecutePendingCallbacks()` here might actually be incorrect, since `EvalMethodGenerator.Execute()` is also called from the JS `eval()` function, and I think in that case the pending callbacks must not yet be executed.

For example:

```js
eval('Promise.resolve().then(function() { console.log(\'2. Promise Continuation\'); });');
console.log('1. After Eval');
```

Running this script in Chrome, Firefox or Edge prints:
```
1. After Eval
2. Promise Continuation
```
However, running it with the current Jurassic from master branch prints:
```
2. Promise Continuation
1. After Eval
```

Comment (paulbartrum) [reply Jurassic/Compiler/MethodGenerator/EvalMethodGenerator.cs]: I did a fix for this 1ce0ed29adef30717e54a3ea7c771020a6bf2c72

**Comment by paulbartrum** [comment]
> note that this method is currently only called from GlobalMethodGenerator.Execute() and EvalMethodGenerator.Execute(). However, e.g. if the script has registered some callbacks (FunctionInstance) which I want to call later (after Execute() returned), I would call FunctionInstance.CallLateBound(), but that does not execute the pending callbacks which the script registered during execution of that function.

Not sure I understand this. If ScriptEngine.Execute() has been called then the pending callbacks list is empty. If you need to call a function and also execute all pending callbacks, then just use Execute or Compile.

**Comment by paulbartrum** [comment]
I made `AddPendingCallback` internal for now. I would rather people use the (stable, documented) promise APIs rather than interface with the engine directly.

**Comment by kpreisser** [comment]
Hi @paulbartrum 
> Not sure I understand this. If ScriptEngine.Execute() has been called then the pending callbacks list is empty. If you need to call a function and also execute all pending callbacks, then just use Execute or Compile.

Sorry, I'm not sure if I follow here. How would I call a `FunctionInstance` using `ScriptEngine.Execute()` or `Evaluate()`?

For example, let's assume I want to write a script host providing a global `setTimeout()` function, where a script can register a callback to be executed later (and when it is called, some counter value is passed as argument to that callback). 

I can implement that function as follows:
```c#
    var engine = new ScriptEngine();
    engine.ForceStrictMode = true;
    engine.SetGlobalValue("console", new FirebugConsole(engine));

    object scriptSyncRoot = new object();

    int counter = 0;
    engine.SetGlobalFunction("setTimeout", new Action<FunctionInstance, int>((handler, timeout) =>
    {
        Task.Delay(timeout).ContinueWith(result =>
        {
            lock (scriptSyncRoot)
            {
                counter++;
                handler.CallLateBound(engine.Global, counter);
                // TODO: Need to call engine.ExecutePendingCallbacks() here...
            }
        }, TaskContinuationOptions.ExecuteSynchronously);
    }));
```

Now, assume I want to write a script that uses the `setTimeout()` to implement a `Promise`-based `delayAsync()` method (similar to `Task.Delay()` in .NET). With [async functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) (ECMAScript 2017), I could write the JavaScript code like this (which can then be downlevel-compiled to ECMAScript 5 e.g. by TypeScript):

```js
function delayAsync(timeout) {
    return new Promise(resolve => setTimeout(resolve, timeout));
}

(async function () {
    for (let i = 0; i < 10; i++) {
        // Wait 1 second.
        let delayCounter = await delayAsync(1000);
        // Print the counter value.
        console.log('DelayCounter: ' + delayCounter);
    }
})();
```

I can then execute the equivalent ES5 code (similar to the one in the following string literal) with Jurassic:
```c#
    lock (scriptSyncRoot)
    {
        engine.Execute(@"

function delayAsync(timeout) {
    return new Promise(function(resolve) { 
        setTimeout(resolve, timeout);
    });
}

(function () {
    var i = 0;
    function loop() {
        if (i < 10) {
            // Wait 1 second.
            delayAsync(1000).then(function (delayCounter) {
                // Print the counter value.
                console.log('DelayCounter: ' + delayCounter);
                i++;

                loop();
            });
        }
    }
    loop();
})();

");
    }
```

However, when I run that, nothing happens, because the pending callbacks are not executed after the call to the supplied `FunctionInstance` returns.
To fix this, I would need to call `engine.ExecutePendingCallbacks()` at the place marked by the comment. After that change, you can see that numbers 1 to 10 are printed to the console (with a delay of 1 second).

Is there another way to do this without having to make `ExecutePendingCallbacks()` public?
Thank you!

**Comment by paulbartrum** [comment]
This should work: `engine.Execute("")` :-)

**Comment by paulbartrum** [comment]
Your event loop code could look something like this:
```c#
var engine = new ScriptEngine();
engine.ForceStrictMode = true;
engine.SetGlobalValue("console", new FirebugConsole(engine));

int someValue = 0;
engine.SetGlobalFunction("setTimeout", new Action<FunctionInstance, int>((handler, timeout) =>
{
    Task.Delay(timeout).ContinueWith(_ =>
    {
        taskQueue.Add(() =>
        {
            someValue++;
            handler.CallLateBound(engine.Global, someValue);
            engine.Execute("");
        });
    });
}));

taskQueue.Add(() =>
{
    engine.Execute("// script goes here");
});

Task.Run(() =>
{
    foreach (var task in taskQueue.GetConsumingEnumerable())
    {
        task();
    }
});
```

**Comment by paulbartrum** [comment]
I committed a change to make this pattern (`Execute("")`) more efficient (f6de4691011d738b0e529ac357aad5170f5df4e0).

**Comment by kpreisser** [comment]
Hi @paulbartrum,
> This should work: `engine.Execute("")` :-)

You're right, that works, though it still looks a bit like a work-around (though with your latest change it at least doesn't compile and execute that empty code any more).

I could also imagine to have a `Execute(params ScriptSource[] sources)` method, that is defined to run all the sources, and then do the "post-processing" which currently means executing pending callbacks. I could then just call `Execute()` with no parameters after `FunctionInstance.CallLateBound()`.

(I see that you protected execution of `ExecutePendingCallbacks()` to do nothing if it is already being called. Maybe we should move that wrapping code into `Execute()` and `Evaluate`, because otherwise it can also happen that I call a `FunctionInstance`, which might callback a CLR method that also calls `Execute()`. This would ensure that `ExecutePendingCallbacks()` is only called if the outermost `ScriptEngine.Execute()` is about to return.)

Thanks!

**Comment by paulbartrum** [comment]
This is not really general enough unfortunately. There's plenty of ways to execute code other than by calling a function directly (for example, you could call `ArrayInstance.Every` with a callback).

I could do something like:
```c#
engine.Execute(() => handler.CallLateBound(engine.Global, someValue))
```
But I think what we have is fine for now.

By the way, the reason why I'm trying to avoid exposing functionality related to pending callbacks list is because I think there's a reasonable chance I will have to build full event loop support at some point, and anything I build now is likely not going to work in the general case. For details on how pending callbacks (officially called a "microtask queue") are related to event loops, see here: https://javascript.info/microtask-queue

**Comment by jcdickinson** [comment]
You could make the script parameter for `Execute` optional (or add an overload) so it becomes the *slightly* less hacky looking: `engine.Execute()`.
